title: ["My portfolio"]
description: ["Hello my name is [Giovani Pedroso](https://github.com/Giovani-Pedroso) and I am an electrical engineer below you will find some of my previous projects"]


theme: jekyll-theme-cayman
